name: Enforce Branching Strategy

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main
      - master

jobs:
  enforce-branching:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        if: github.event.pull_request.head.ref != 'dev'
        run: |
          echo "Error: PRs to main/master must come from dev branch only"
          echo "This PR is from '${{ github.event.pull_request.head.ref }}' to '${{ github.event.pull_request.base.ref }}'"
          exit 1

      - name: Close PR if not from dev branch
        if: github.event.pull_request.head.ref != 'dev' && failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo;
            
            // Add comment explaining why PR is being closed
            await github.rest.issues.createComment({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: prNumber,
              body: "⚠️ **This PR has been automatically closed** ⚠️\n\nAccording to our branching strategy, PRs can only be merged into `main`/`master` from the `dev` branch.\n\nPlease create a new PR that targets the `dev` branch instead, or change the base of this PR to `dev`."
            });
            
            // Close the PR
            await github.rest.pulls.update({
              owner: repo.owner,
              repo: repo.repo,
              pull_number: prNumber,
              state: 'closed'
            });
            
            console.log(`PR #${prNumber} was automatically closed because it didn't originate from the dev branch.`);