name: "Labels: Untriaged"

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write        
      pull-requests: write 
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        # The condition checks if the labels array is empty
        if: ${{ join(github.event.issue.labels, '') == '' }}
        with:
          labels: "S: Untriaged"
